### ISSUE TITLE
Suggestion: License

### ISSUE THREAD

**Issue by ebektas** [Weyaxi/open-llm-leaderboard-tracker#1]
I strongly suggest adding an appropriate license to the project such as MIT or Apache 2.0 that respects the licensing requirements of the libraries used. Keep up the good work.

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by Weyaxi** [comment]
Thank you for your suggestion! As of now, I have added the MIT license to the project repository.
